version: "3.6"

services:
    nats-1:
        image: nats:2.1.8-alpine3.11
        networks:
            nat-cluster_net:
              ipv4_address: 172.16.230.100
        command: 
            - "--debug"
            - "--cluster"
            - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port" 
            - "4222"
        ports: 
            - "14222:4222"
            - "18222:8222"
        expose: 
            - 4222
            - 8222
            - 6222
    nats-2:
        image: nats:2.1.8-alpine3.11
        networks:
            nat-cluster_net:
                ipv4_address: 172.16.230.101
        command: 
            - "--debug"
            - "--cluster" 
            - "nats://0.0.0.0:6222"
            - "--http_port"
            - "8222"
            - "--port" 
            - "4222"
            - "--routes" 
            - "nats://nats-1:6222"
        ports: 
            - "14223:4222"
            - "18223:8222"
        expose: 
            - 4222
            - 8222
            - 6222
networks:
    nat-cluster_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
                subnet: 172.16.230.0/24